_wandb:
    value:
        cli_version: 0.25.0
        e:
            ia7nybei6w170vx68i048h5moldxai41:
                args:
                    - --wandb
                    - "False"
                    - --preprocessing
                    - "no"
                    - --performance
                codePath: uci_main_loso_baseline.py
                codePathLocal: uci_main_loso_baseline.py
                email: mrthonglion@gmail.com
                executable: /home/qphan/master-thesis/.venv/bin/python
                git:
                    commit: 2b2326b47514440696189aabb0df8b0a56f33bbe
                    remote: git@github.com:thong-phn/master-thesis.git
                host: student-pc
                os: Linux-6.8.0-55-generic-x86_64-with-glibc2.39
                program: /home/qphan/master-thesis/uci_main_loso_baseline.py
                python: CPython 3.11.14
                root: /home/qphan/master-thesis
                startedAt: "2026-04-09T17:46:06.771882Z"
                writerId: ia7nybei6w170vx68i048h5moldxai41
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: UCI-HAR
epochs:
    value: 60
lr:
    value: 0.001
model:
    value: SeparableConvCNN
performance:
    value: true
preprocessing:
    value: "no"
test_subjects:
    value:
        - 2
        - 4
        - 9
        - 10
        - 12
        - 13
        - 18
        - 20
        - 24
train_subjects:
    value:
        - 3
        - 5
        - 6
        - 7
        - 8
        - 11
        - 14
        - 15
        - 16
        - 17
        - 19
        - 21
        - 22
        - 23
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
val_subjects:
    value:
        - 1
