_wandb:
    value:
        cli_version: 0.25.0
        e:
            yft9l77jbnxdbazk521firb6688kd3el:
                args:
                    - --single_subject_only
                    - "7"
                    - --run_name
                    - S7tuning-wCEL
                    - --sparsity_weight_bin
                    - "0.2"
                    - --stage1_model_path
                    - /home/qphan/master-thesis/models/wear_best_model_five_stage_subject7_val_stage1.pth
                codePath: wear_main_loso_input_pruning.py
                codePathLocal: wear_main_loso_input_pruning.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "132445769728"
                        used: "53189910528"
                email: mrthonglion@gmail.com
                executable: /home/qphan/anaconda3/envs/py311-litert-torch/bin/python
                git:
                    commit: e0179dae0a92c0ede53d10cb352fc4e0d1d1caee
                    remote: git@github.com:thong-phn/master-thesis.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-f6085285-18c3-339e-ebc0-f4b07899e0b8
                    - architecture: Pascal
                      cudaCores: 384
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce GT 1030
                      uuid: GPU-7c331ecd-03fc-d368-3e36-b625e6cf52ba
                host: student-pc
                memory:
                    total: "67337535488"
                os: Linux-6.8.0-55-generic-x86_64-with-glibc2.39
                program: /home/qphan/master-thesis/wear_main_loso_input_pruning.py
                python: CPython 3.11.14
                root: /home/qphan/master-thesis
                startedAt: "2026-04-04T10:42:59.149889Z"
                writerId: yft9l77jbnxdbazk521firb6688kd3el
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
dataset:
    value: WEAR
fold_count:
    value: 1
preprocessing:
    value: fft
results_log_path:
    value: /home/qphan/master-thesis/log/wear_loso_three_stage_results_fft.txt
sparsity_weight_bin:
    value: 0.2
training_type:
    value: three_stage
