cd ..

# # Input pruning
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.05 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.1 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.2 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.3 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.4 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.5 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.6 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.7 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.8 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 1.0 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 2.0 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'fft' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth' --performance

# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.05 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.1 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.2 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.3 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.4 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.5 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.6 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.7 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.8 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
python uci_main_loso_input_pruning.py --sparsity_weight_bin 1.0 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
python uci_main_loso_input_pruning.py --sparsity_weight_bin 1.5 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance
python uci_main_loso_input_pruning.py --sparsity_weight_bin 1.8 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'ihw' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth' --performance

# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.05 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.1 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.2 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.3 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.4 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.5 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.6 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.7 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 0.8 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 1.0 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance
# python uci_main_loso_input_pruning.py --sparsity_weight_bin 2.0 --wandb True --run_name 'InputPruningFineTuned' --preprocessing 'dct' --stage1_model_path '/home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth' --performance

# Channel pruning
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.1 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.2 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.3 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.4 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.5 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.6 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.7 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 0.8 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 1.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing fft --sparsity_weight 2.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/fft/uci_best_model_subject{subject}_val.pth 

# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.1 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.2 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.3 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.4 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.5 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.6 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.7 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 0.8 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 1.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing dct --sparsity_weight 2.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/dct/uci_best_model_subject{subject}_val.pth 

# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.1 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.2 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.3 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.4 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.5 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.6 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.7 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 0.8 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 1.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 
# python uci_main_loso_channel_pruning.py --preprocessing ihw --sparsity_weight 2.0 --wandb 1 --performance --run_name "ChannelPruningFineTuned" --stage1_model_path /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth 

