_wandb:
    value:
        cli_version: 0.25.0
        e:
            pqzp7lkrfez2bewzpplaisizc53opvxo:
                args:
                    - --sparsity_weight_bin
                    - "0.1"
                    - --wandb
                    - "True"
                    - --run_name
                    - InputPruningFineTuned
                    - --preprocessing
                    - ihw
                    - --stage1_model_path
                    - /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject{subject}_val.pth
                    - --performance
                codePath: uci_main_loso_input_pruning.py
                codePathLocal: uci_main_loso_input_pruning.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "132445769728"
                        used: "52884533248"
                email: mrthonglion@gmail.com
                executable: /home/qphan/master-thesis/.venv/bin/python
                git:
                    commit: b12ff4019cb9e67f08a7af5134477b48e71f85e2
                    remote: git@github.com:thong-phn/master-thesis.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-f6085285-18c3-339e-ebc0-f4b07899e0b8
                    - architecture: Pascal
                      cudaCores: 384
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce GT 1030
                      uuid: GPU-7c331ecd-03fc-d368-3e36-b625e6cf52ba
                host: student-pc
                memory:
                    total: "67337535488"
                os: Linux-6.8.0-55-generic-x86_64-with-glibc2.39
                program: /home/qphan/master-thesis/uci_main_loso_input_pruning.py
                python: CPython 3.11.14
                root: /home/qphan/master-thesis
                startedAt: "2026-04-09T22:27:46.278505Z"
                writerId: pqzp7lkrfez2bewzpplaisizc53opvxo
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
        visualize:
            stage_1_separableconvcnn/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage_1_separableconvcnn/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            stage_3_separableconvcnn/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage_3_separableconvcnn/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
dataset:
    value: UCI-HAR
epochs_stage1:
    value: 60
epochs_stage2:
    value: 60
epochs_stage3:
    value: 60
lr:
    value: 0.001
performance:
    value: true
preprocessing:
    value: ihw
selected_subjects:
    value:
        - 1
        - 3
        - 5
        - 6
        - 7
        - 8
        - 11
        - 14
        - 15
        - 16
        - 17
        - 19
        - 21
        - 22
        - 23
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
sparsity_weight_bin:
    value: 0.1
stage1_model_path:
    value: /home/qphan/master-thesis/models/uci/stage1/ihw/uci_best_model_subject16_val.pth
stage2_backbone_lr_factor:
    value: 0.1
stage2_model_path:
    value: null
stage3_model_path:
    value: null
test_subjects:
    value:
        - 2
        - 4
        - 9
        - 10
        - 12
        - 13
        - 18
        - 20
        - 24
train_subjects:
    value:
        - 1
        - 3
        - 5
        - 6
        - 7
        - 8
        - 11
        - 14
        - 15
        - 17
        - 19
        - 21
        - 22
        - 23
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
training_type:
    value: three_stage
val_subjects:
    value:
        - 16
