_wandb:
    value:
        cli_version: 0.25.0
        e:
            jv2uh9el06ehq16hewmzm43omfy81rww:
                args:
                    - --preprocessing
                    - dct
                    - --wandb_run_name
                    - Baseline-DCT
                    - --model
                    - SeparableConvCNN
                codePath: wear_main_loso_baseline.py
                codePathLocal: wear_main_loso_baseline.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "132445769728"
                        used: "53190049792"
                email: mrthonglion@gmail.com
                executable: /home/qphan/anaconda3/envs/py311-litert-torch/bin/python
                git:
                    commit: e0179dae0a92c0ede53d10cb352fc4e0d1d1caee
                    remote: git@github.com:thong-phn/master-thesis.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-f6085285-18c3-339e-ebc0-f4b07899e0b8
                    - architecture: Pascal
                      cudaCores: 384
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce GT 1030
                      uuid: GPU-7c331ecd-03fc-d368-3e36-b625e6cf52ba
                host: student-pc
                memory:
                    total: "67337535488"
                os: Linux-6.8.0-55-generic-x86_64-with-glibc2.39
                program: /home/qphan/master-thesis/wear_main_loso_baseline.py
                python: CPython 3.11.14
                root: /home/qphan/master-thesis
                startedAt: "2026-04-04T11:42:47.223309Z"
                writerId: jv2uh9el06ehq16hewmzm43omfy81rww
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
        visualize:
            stage_1_separableconvcnn/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: stage_1_separableconvcnn/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
dataset:
    value: WEAR
epochs:
    value: 60
lr:
    value: 0.001
model:
    value: SeparableConvCNN
preprocessing:
    value: dct
test_subjects:
    value:
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
train_subjects:
    value:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
val_subjects:
    value:
        - 9
